/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jinliang_testgradle_utils_NDKJNIUtils */

#ifndef _Included_com_example_jinliang_testgradle_utils_NDKJNIUtils
#define _Included_com_example_jinliang_testgradle_utils_NDKJNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jinliang_testgradle_utils_NDKJNIUtils
 * Method:    getAddString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jinliang_testgradle_utils_NDKJNIUtils_getAddString
  (JNIEnv *env, jobject){
   return  env->NewStringUTF("这是我的info");
};

#ifdef __cplusplus
}
#endif
#endif
